const SUPABASE_URL='https://vslbpjbvydxleufpmkhp.supabase.co',SUPABASE_KEY='sb_publishable_jpPPDLwsvPY5mJjGWZYRtA_uJl4du2L',ADMIN='info@radikal-surf.com';let db;
const defaults={hero_wind_title:'RÜZGÂRIN<br><em>PEŞİNDE.</em>',hero_kite_title:'GÖKYÜZÜ<br><em>SENİN.</em>',intro_title:'ADAMIZ,<br><em>SINIFIMIZ.</em>',intro_lead:'Rüzgar bizim dilimiz, su bizim alanımız. Gökçeada’nın vahşi batı kıyısında ilk sürüşleri ömür boyu süren bir tutkuya dönüştürüyoruz.',wind_title:'RÜZGAR<br>SÖRFÜ',wind_caption:'Detayları gör <i>↗</i>',kite_title:'KITE<br>SURF',kite_caption:'Detayları gör <i>↗</i>',wing_title:'WING<br>FOIL',wing_caption:'Detayları gör <i>↗</i>',contact_title:'KIYININ<br><em>UCUNDA</em> BULUŞALIM.',phone:'+90 532 271 58 59',instagram:'@radikalsurfgokceada',location:'Aydıncık, Gökçeada / Türkiye'};
const images={hero_wind_image:'',hero_kite_image:'',wind_image:'assets/windsurf-radikal.png',kite_image:'assets/kite-card.jpeg',wing_image:'assets/wingfoil-radikal.jpg',gallery_1:'assets/galeri-8.jpeg',gallery_2:'assets/galeri-5.jpg',gallery_3:'assets/archive-kite-shore.jpeg',gallery_4:'assets/archive-kite-carve.jpeg',gallery_5:'assets/archive-kite-coaching.jpeg',gallery_6:'assets/archive-kite-air.jpeg',gallery_7:'assets/archive-instructor.jpeg',gallery_8:'assets/archive-kite-student.jpg'};
const labels={hero_wind_title:'Rüzgar sörfü hero başlığı',hero_kite_title:'Kite surf hero başlığı',intro_title:'Tanıtım başlığı',intro_lead:'Tanıtım metni',wind_title:'Rüzgar sörfü kart başlığı',wind_caption:'Rüzgar sörfü kart alt metni',kite_title:'Kite surf kart başlığı',kite_caption:'Kite surf kart alt metni',wing_title:'Wingfoil kart başlığı',wing_caption:'Wingfoil kart alt metni',contact_title:'İletişim başlığı',phone:'Telefon',instagram:'Instagram kullanıcı adı',location:'Konum metni'};let content={...defaults,...images};
const qs=s=>document.querySelector(s),show=(el,on)=>{el.classList.toggle('hidden',!on);if(el.id==='app')el.style.display=on?'block':''},notice=(id,msg)=>{const el=qs(id);el.textContent=msg;show(el,true)};
const cleanText=value=>String(value||'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]*>/g,'').trim();function render(){qs('#textFields').innerHTML=Object.entries(labels).map(([key,label])=>`<label class="field">${label}<textarea data-key="${key}">${cleanText(content[key]||'')}</textarea></label>`).join('');qs('#imageFields').innerHTML=Object.keys(images).map(key=>`<label class="field image-field">${key.replaceAll('_',' ')}<img src="${cleanText(content[key]||'')}" alt=""><input data-image="${key}" value="${cleanText(content[key]||'')}" placeholder="Görsel URL"><input data-upload="${key}" type="file" accept="image/*"></label>`).join('');document.querySelectorAll('[data-upload]').forEach(input=>input.onchange=upload)}
async function load(){const{data,error}=await db.from('site_content').select('content').eq('id','site').maybeSingle();if(error)throw error;content={...content,...(data?.content||{})};render()}
async function upload(e){const file=e.target.files[0],key=e.target.dataset.upload;if(!file)return;notice('#status','Görsel yükleniyor…');const path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`,{error}=await db.storage.from('site-media').upload(path,file,{upsert:false});if(error)return notice('#status',error.message);const{data}=db.storage.from('site-media').getPublicUrl(path);content[key]=data.publicUrl;render();notice('#status','Görsel yüklendi. Kaydetmeyi unutma.')}
async function signedIn(){const{data:{session}}=await db.auth.getSession();if(!session)return; if(session.user.email!==ADMIN){await db.auth.signOut();return notice('#loginStatus','Bu hesap yönetici olarak yetkili değil.')}show(qs('#login'),false);show(qs('#app'),true);show(qs('#logout'),true);try{await load()}catch(e){notice('#status','Kurulum SQL’i henüz eklenmemiş olabilir: '+e.message)}}
qs('#signIn').onclick=async()=>{const{error}=await db.auth.signInWithPassword({email:qs('#email').value,password:qs('#password').value});if(error)return notice('#loginStatus',error.message);signedIn()};qs('#signUp').onclick=async()=>{const{error}=await db.auth.signUp({email:qs('#email').value,password:qs('#password').value});notice('#loginStatus',error?'Hata: '+error.message:'Hesap oluşturuldu. E-postanı doğruladıktan sonra giriş yap.')};qs('#logout').onclick=()=>db.auth.signOut().then(()=>location.reload());
qs('#editor').onsubmit=async e=>{e.preventDefault();document.querySelectorAll('[data-key]').forEach(x=>content[x.dataset.key]=x.value.replace(/\n/g,'<br>'));document.querySelectorAll('[data-image]').forEach(x=>content[x.dataset.image]=x.value);document.querySelectorAll('[data-price]').forEach(x=>content[x.dataset.price]=x.value);notice('#status','Kaydediliyor…');const{error}=await db.from('site_content').upsert({id:'site',content,updated_at:new Date().toISOString()});notice('#status',error?'Hata: '+error.message:'Kaydedildi. Ana sayfayı yenileyerek değişiklikleri görebilirsin.')};try{db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);if(!db)throw new Error('Supabase bağlantısı yüklenemedi.');signedIn()}catch(error){notice('#loginStatus','Bağlantı hatası: '+error.message)}
